name: Build and Push Docker Image

on:
  push: 
    branches: 
     - main
    tags: 
     - v1.0 

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: login to Dockerhub
        uses: Docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extracr Docker Metadata
        id: meta
        uses: docker/Metadata-action@v3
        with:
          Image: ${{ secrets.DOCKERHUB_USERNAME }}/docker-auto-build
          tags: |
            type=sha,format=short,prefix=   # Short Commit ID (e.g. a1b2c3d)
            type=semver,pattern={{version}} # Git Tag (e.g. v1.0.0)
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }} # Main branch pe 'latest' bhi rakhega   

      - name: build and push Docker Image
        uses: docker/build-push-action@v4
        with:
          context:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/docker-auto-build:latest    